---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-parent
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: namespaces/argocd/test
    repoURL: https://github.com/spezam/monitoring.git
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated: null
