---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/test
    repoURL: 'https://github.com/spezam/grafana.git'
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated: null
